// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqHo5GxcDfGndu08J3OtIty1s4j1vFgs',
    appId: '1:602486709132:web:9d6c41daf03ff2169714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    authDomain: 'imagesignup-a2764.firebaseapp.com',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
    measurementId: 'G-13W0DNF6FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXP2Kom5O9vhJPe51EqGi51yi6Ea7Yjcc',
    appId: '1:602486709132:android:ce652fa9b387ab9c9714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLKIMiWq0nGahpQFNWcNi6OY3TokY9rg8',
    appId: '1:602486709132:ios:09a37d75638a0baf9714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
    androidClientId: '602486709132-mk1o6dgv9ej3p37ld6u9e8e3iv8jr4qe.apps.googleusercontent.com',
    iosClientId: '602486709132-60a7fegedpaqdh5uj2ut0h00kc8g15ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLKIMiWq0nGahpQFNWcNi6OY3TokY9rg8',
    appId: '1:602486709132:ios:09a37d75638a0baf9714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
    androidClientId: '602486709132-mk1o6dgv9ej3p37ld6u9e8e3iv8jr4qe.apps.googleusercontent.com',
    iosClientId: '602486709132-60a7fegedpaqdh5uj2ut0h00kc8g15ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqHo5GxcDfGndu08J3OtIty1s4j1vFgs',
    appId: '1:602486709132:web:6e7bc11a3693144b9714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    authDomain: 'imagesignup-a2764.firebaseapp.com',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
    measurementId: 'G-TRYFSVJTR5',
  );

}